const tripMeta = {
  title: "2026 杭州・烏鎮・上海行程",
  dateRange: "2026-06-06 to 2026-06-11",
  datesLabel: "2026/6/6 - 2026/6/11",
  nights: "6 天 5 夜",
  cities: ["杭州", "烏鎮", "上海"],
  route: ["上海虹橋", "杭州", "烏鎮", "上海", "上海虹橋返台"],
  theme: "南宋文化、西湖、江南水鄉、上海外灘與老城",
};

const images = {
  hero: "./assets/west-lake.jpg",
  westLake: "./assets/west-lake.jpg",
  wuzhen: "./assets/wuzhen-night.jpg",
  bund: "./assets/bund-night.png",
  deshou: "./assets/deshou-palace.jpg",
  banquet: "./assets/song-banquet.jpg",
  southernSongStreet: "./assets/southern-song-street.jpg",
  hefangStreet: "./assets/hefang-street.jpg",
  westLakeHubin: "./assets/hubin-west-lake.jpg",
  lingyin: "./assets/lingyin-temple.jpg",
  meijiawu: "./assets/meijiawu-tea.jpg",
  westLakeEssence: "./assets/west-lake-essence.jpg",
  wuzhenXizha: "./assets/wuzhen-xizha.jpg",
  wuzhenDongzha: "./assets/wuzhen-dongzha.jpg",
  yuyuan: "./assets/yuyuan-garden.jpg",
  chenghuang: "./assets/chenghuang-temple.jpg",
  nanjingRoad: "./assets/nanjing-road.jpg",
  bundSkyline: "./assets/bund-skyline.jpg",
};

const flights = [
  {
    id: "arrival-flight",
    date: "2026-06-06",
    label: "去程",
    direction: "台北 → 上海",
    flightNo: "CA198",
    departAirport: "台北松山 TSA",
    arriveAirport: "上海虹橋 SHA",
    arrivalTime: "17:10",
    status: "已訂",
    note: "抵達後直接轉高鐵前往杭州",
  },
  {
    id: "return-flight",
    date: "2026-06-11",
    label: "回程",
    direction: "上海 → 台北",
    flightNo: "CA197",
    departAirport: "上海虹橋 SHA",
    arriveAirport: "台北松山 TSA",
    departureTime: "12:15",
    status: "已訂",
    note: "當天不安排正式景點",
  },
];

const itineraryDays = [
  {
    date: "2026-06-06",
    day: "週六",
    city: "杭州",
    hotelCity: "杭州",
    title: "抵達上海虹橋，轉高鐵到杭州",
    focus: "順利入境、銜接高鐵、武林夜市、早點休息",
    note: "若行程順利晚上可以到武林夜市逛逛，或是直接進酒店休息。",
    events: [
      {
        time: "17:10",
        title: "抵達上海虹橋機場",
        type: "transport",
        required: true,
        detail: "抵達後不進上海市區，直接銜接上海虹橋火車站。",
      },
      {
        time: "18:30-20:00",
        title: "上海虹橋站搭高鐵前往杭州",
        type: "transport",
        required: true,
        detail: "建議抓 18:30-20:00 之間班次，保留入境、領行李與步行轉乘時間。",
      },
      {
        time: "晚間",
        title: "杭州飯店入住與簡單晚餐",
        type: "hotel",
        required: true,
        detail: "6/6-6/8 住杭州；抵達後以入住、簡單晚餐與休息為主。",
      },
    ],
  },
  {
    date: "2026-06-07",
    day: "週日",
    city: "杭州",
    hotelCity: "杭州",
    title: "杭州宮宴、德壽宮、南宋老街",
    focus: "杭州宮宴治裝午宴、德壽宮、老街慢走",
    note: "杭州宮宴午宴若要治裝，10:00 就要到現場；德壽宮改排在宮宴後面。",
    events: [
      {
        time: "10:00-中午",
        title: "杭州宮宴治裝與午宴",
        type: "food",
        required: true,
        reservation: true,
        detail: "午宴若要治裝，10:00 需抵達現場，先完成服裝、妝髮與入席準備。",
      },
      {
        time: "下午",
        title: "德壽宮",
        type: "culture",
        required: true,
        reservation: true,
        detail: "本次杭州南宋文化線的核心景點；改排宮宴後面，需確認 6/7 下午預約時段。",
      },
      {
        time: "下午晚些",
        title: "南宋御街",
        type: "culture",
        required: true,
        detail: "從德壽宮過渡到杭州老城街區，全長約 4,185 公尺。",
      },
      {
        time: "傍晚",
        title: "河坊街／清河坊，視體力補西湖湖濱",
        type: "shopping",
        required: true,
        detail: "小吃、老字號、茶葉與手工藝集中；若體力足夠，再補湖濱短散步。",
      },
    ],
  },
  {
    date: "2026-06-08",
    day: "週一",
    city: "杭州 → 烏鎮",
    hotelCity: "烏鎮",
    title: "靈隱寺、茶村、西湖，傍晚入住烏鎮",
    focus: "山林寺院、龍井茶、西湖精華、烏鎮夜景",
    note: "杭州段收尾後移動到烏鎮，開始連住兩晚。",
    events: [
      {
        time: "上午",
        title: "靈隱寺",
        type: "culture",
        required: true,
        detail: "適合安排在早上，山林、古剎、飛來峰石刻與香火氣氛都很完整。",
      },
      {
        time: "中午",
        title: "梅家塢／龍井茶村",
        type: "food",
        required: false,
        detail: "改為可選安排；若時間與體力允許，再用午餐與品茶感受龍井茶村生活。",
      },
      {
        time: "下午",
        title: "西湖精華段",
        type: "nature",
        required: true,
        detail: "不硬走整圈，可依體力選湖濱白堤、船遊三潭印月或蘇堤拍照線。",
      },
      {
        time: "16:00-18:30",
        title: "杭州前往烏鎮",
        type: "transport",
        required: true,
        detail: "6/8-6/10 住烏鎮；若同行家人較多或行李多，包車會比轉車舒服。",
      },
      {
        time: "晚上",
        title: "烏鎮西柵夜景",
        type: "nightview",
        required: true,
        detail: "小橋、河道與水岸夜景是烏鎮住進景區最大的價值。",
      },
    ],
  },
  {
    date: "2026-06-09",
    day: "週二",
    city: "烏鎮",
    hotelCity: "烏鎮",
    title: "烏鎮完整慢遊日",
    focus: "西柵清晨、深度散步、東柵可選、續住烏鎮",
    note: "今天不移動到上海，節奏留給烏鎮本身。",
    events: [
      {
        time: "清晨",
        title: "烏鎮西柵清晨散步",
        type: "nature",
        required: true,
        detail: "住在景區內的好處是能避開白天人潮，看到比較安靜的水鄉。",
      },
      {
        time: "上午",
        title: "西柵深度散步",
        type: "culture",
        required: true,
        detail: "把橋、水巷、老宅、茶館與水岸慢慢走完，不急著趕下一座城市。",
      },
      {
        time: "下午",
        title: "東柵可選，或回西柵休息",
        type: "optional",
        required: false,
        detail: "完整版烏鎮加東柵；慢遊版留在西柵喝茶、拍照或回住宿休息。",
      },
      {
        time: "晚上",
        title: "續住烏鎮，再看一次西柵夜景",
        type: "nightview",
        required: true,
        detail: "第二晚不用趕路，可以挑人少的河段散步或安排景區內晚餐。",
      },
    ],
  },
  {
    date: "2026-06-10",
    day: "週三",
    city: "烏鎮 → 上海",
    hotelCity: "上海",
    title: "烏鎮收尾，入住上海中心J飯店，外灘老城半日",
    focus: "烏鎮退房、上海中心J飯店入住、豫園、城隍廟、外灘",
    note: "上海段只保留外灘、城隍廟、豫園，讓最後一晚維持精簡好走。",
    events: [
      {
        time: "上午",
        title: "烏鎮退房與最後散步",
        type: "nature",
        required: true,
        detail: "保留輕鬆收尾時間，不把上午塞滿。",
      },
      {
        time: "中午前後",
        title: "烏鎮前往上海中心J飯店",
        type: "transport",
        required: true,
        detail: "6/10-6/11 住上海中心J飯店；包車約 2-3 小時，高鐵通常需先到桐鄉站再轉上海。",
      },
      {
        time: "下午",
        title: "豫園＋城隍廟",
        type: "culture",
        required: true,
        detail: "上海老城精華集中，從古典園林接到城隍廟商圈最順。",
      },
      {
        time: "傍晚到晚上",
        title: "外灘夜景",
        type: "nightview",
        required: true,
        detail: "從外灘看黃浦江、萬國建築群與浦東天際線；住陸家嘴，來回動線也好安排。",
      },
    ],
  },
  {
    date: "2026-06-11",
    day: "週四",
    city: "上海",
    hotelCity: "回台",
    title: "上海虹橋返台",
    focus: "早餐、退房、前往虹橋機場",
    note: "中午航班，不排正式景點。",
    events: [
      {
        time: "07:30-08:00",
        title: "上海中心J飯店五星級頂級早餐與整理行李",
        type: "food",
        required: true,
        detail: "先好好享用飯店頂級早餐，再整理行李退房；最多只安排飯店附近短散步或買伴手禮。",
      },
      {
        time: "09:30-10:00",
        title: "專車前往虹橋機場",
        type: "transport",
        required: true,
        detail: "從上海中心J飯店安排專車直達上海虹橋機場。",
      },
      {
        time: "12:15",
        title: "上海虹橋起飛返台",
        type: "flight",
        required: true,
        detail: "實際報到與登機時間仍以航空公司通知為準。",
      },
    ],
  },
];

const hotelCandidates = {
  hangzhou: [
    {
      name: "Pagoda君亭設計飯店（杭州西湖·武林廣場店）",
      stayDates: "6/6-6/8",
      rating: 9.3,
      stars: 5,
      area: "武林廣場／西湖商圈",
      landmark: "近武林廣場",
      priority: "confirmed",
      link: "https://tw.trip.com/hotels/hangzhou-hotel-detail-435431/pagoda-hotelhangzhou-west-lake-wulin-plaza/",
      note: "已確認住杭州兩晚。位置靠近武林廣場，適合銜接抵達後的武林夜市或直接回飯店休息。",
    },
  ],
  wuzhen: [
    {
      name: "烏鎮民宿",
      stayDates: "6/8-6/10",
      rating: 9.4,
      stars: 4,
      area: "西柵景區內",
      landmark: "西柵景區內",
      priority: "confirmed",
      link: "https://www.ewuzhen.com/hotel/detail?goodsId=215133133731807234&goodsCode=HT-202002-8033&livesDate=2023-08-03&outDate=2023-08-04",
      note: "已確認住烏鎮兩晚。官方烏鎮旅遊預訂網連結，建議再確認是否含西柵門票、行李運送與景區接駁；入住時記得向老闆預約早茶客。",
    },
  ],
  shanghai: [
    {
      name: "上海中心J飯店",
      stayDates: "6/10-6/11",
      rating: "",
      stars: "",
      area: "上海中心／陸家嘴",
      landmark: "上海中心／陸家嘴",
      priority: "confirmed",
      link: "https://www.jhotel-shanghai.com/zh-hans/shanghai-luxury-hotel-rooms-and-suites/stateroom/",
      note: "已確認住上海一晚，入住全球第三高大樓上海中心J飯店。連結為祥云客房頁面，上海段只保留外灘、城隍廟、豫園。",
    },
  ],
};

const places = [
  {
    name: "德壽宮",
    city: "杭州",
    type: "南宋遺址",
    day: "6/7 下午",
    priority: "必排",
    image: images.deshou,
    hours: "約 9:30-17:00，週一閉館",
    reminder: "排在杭州宮宴後，需預約 6/7 下午時段。",
    description:
      "本次杭州南宋文化線的核心景點，可以理解南宋臨安宮廷生活與宋韻美學。",
  },
  {
    name: "杭州宮宴",
    city: "杭州",
    type: "沉浸式餐宴",
    day: "6/7 10:00-中午",
    priority: "必排",
    image: images.banquet,
    hours: "10:00 到場治裝，依午宴場次",
    reminder: "午宴若要治裝，10:00 需抵達現場。",
    description:
      "融合宮廷服飾、禮儀、歌舞與中式宴席，是本次餐飲重點體驗。",
  },
  {
    name: "南宋御街",
    city: "杭州",
    type: "歷史街區",
    day: "6/7 下午",
    priority: "必排",
    image: images.southernSongStreet,
    hours: "街區型景點",
    reminder: "接在德壽宮後慢走最順。",
    description:
      "宋韻感集中的街區，連結宮廷、老城、商業街與市井生活。",
  },
  {
    name: "河坊街／清河坊",
    city: "杭州",
    type: "古街小吃",
    day: "6/7 下午",
    priority: "必排",
    image: images.hefangStreet,
    hours: "街區型景點",
    reminder: "適合作為杭州老城散步收尾。",
    description:
      "杭州保存較完整的古城區之一，有小吃、老字號、茶葉與手工藝。",
  },
  {
    name: "西湖湖濱",
    city: "杭州",
    type: "湖景散步",
    day: "6/7 可選",
    priority: "可選",
    image: images.westLakeHubin,
    hours: "開放式景區",
    reminder: "6/7 下午視體力補上。",
    description:
      "若老街行程結束後體力還夠，可補一段湖濱短散步，不硬排長時間遊湖。",
  },
  {
    name: "靈隱寺",
    city: "杭州",
    type: "佛寺",
    day: "6/8 上午",
    priority: "必排",
    image: images.lingyin,
    hours: "約 7:00-18:00",
    reminder: "飛來峰景區與靈隱寺分別收費。",
    description:
      "杭州最具代表性的寺院之一，適合早上安排山林、古剎與石刻。",
  },
  {
    name: "梅家塢茶村",
    city: "杭州",
    type: "茶文化",
    day: "6/8 中午",
    priority: "可選",
    image: images.meijiawu,
    hours: "依茶館與餐廳",
    reminder: "已改為可選，視 6/8 時間與體力安排。",
    description:
      "龍井茶重要產區，可把午餐、茶村、茶館與茶山放在一起安排。",
  },
  {
    name: "西湖精華段",
    city: "杭州",
    type: "湖景",
    day: "6/8 下午",
    priority: "必排",
    image: images.westLakeEssence,
    hours: "開放式景區",
    reminder: "不用硬走整圈，可選精華段。",
    description:
      "可選湖濱白堤、船遊三潭印月、蘇堤花港觀魚或雷峰塔外觀。",
  },
  {
    name: "烏鎮西柵",
    city: "烏鎮",
    type: "水鄉夜景",
    day: "6/8 晚、6/9",
    priority: "必排",
    image: images.wuzhenXizha,
    hours: "約 9:00-22:00",
    reminder: "住宿最好確認是否含門票與接駁；入住時向老闆預約早茶客。",
    description:
      "這次烏鎮住兩晚，西柵可看夜景、清晨與白天三種不同節奏。",
  },
  {
    name: "烏鎮東柵",
    city: "烏鎮",
    type: "傳統水鄉",
    day: "6/9 可選",
    priority: "可選",
    image: images.wuzhenDongzha,
    hours: "依景區公告",
    reminder: "慢遊版可只逛西柵。",
    description:
      "比西柵更偏傳統生活與歷史感，適合想把烏鎮走完整一點時加入。",
  },
  {
    name: "豫園",
    city: "上海",
    type: "古典園林",
    day: "6/10 下午",
    priority: "必排",
    image: images.yuyuan,
    hours: "約 9:00-16:30，週一閉園",
    reminder: "從陸家嘴入住後再前往老城區。",
    description:
      "上海古典園林代表，和城隍廟同區，適合作為上海半日主軸。",
  },
  {
    name: "城隍廟",
    city: "上海",
    type: "老城商圈",
    day: "6/10 下午",
    priority: "必排",
    image: images.chenghuang,
    hours: "依店家與商圈公告",
    reminder: "和豫園安排在同一段最省移動。",
    description:
      "小吃、老字號、街景與豫園商圈集中，可和豫園合併成上海老城半日。",
  },
  {
    name: "南京路步行街",
    city: "上海",
    type: "步行街",
    day: "6/10 可選",
    priority: "可選",
    image: images.nanjingRoad,
    hours: "開放式商圈",
    reminder: "可接在外灘前後，視時間、人潮與體力安排。",
    description:
      "上海代表性的商業步行街，霓虹街景與老字號集中，適合補一段輕鬆散步。",
  },
  {
    name: "外灘",
    city: "上海",
    type: "夜景",
    day: "6/10 傍晚到晚上",
    priority: "必排",
    image: images.bundSkyline,
    hours: "開放式景點",
    reminder: "適合上海唯一一晚安排。",
    description:
      "上海最具代表性的夜景區域之一，可看黃浦江、歷史建築與浦東天際線。",
  },
];

const transfers = [
  {
    title: "6/6 上海虹橋機場 → 上海虹橋火車站 → 杭州",
    time: "18:30-20:00 高鐵",
    note: "直接從虹橋機場搭高鐵到杭州。",
  },
  {
    title: "6/8 杭州 → 烏鎮",
    time: "移動方式待確認",
    note: "需更新杭州到烏鎮的實際移動方式與出發時間。",
  },
  {
    title: "6/10 烏鎮 → 上海中心J飯店",
    time: "中午前後移動",
    note: "6/10-6/11 住上海中心J飯店；包車約 2-3 小時，高鐵轉車通常需先到桐鄉站。",
  },
  {
    title: "6/11 上海中心J飯店 → 上海虹橋機場",
    time: "09:30-10:00 專車出發",
    note: "從上海中心J飯店安排專車直達上海虹橋機場；回程 12:15 起飛。",
  },
];

const checklist = [
  { item: "確認 6/6 航班號與登機時間", status: "pending", category: "flight" },
  { item: "確認 6/11 回程航班號與報到時間", status: "pending", category: "flight" },
  { item: "預約德壽宮 6/7 下午時段", status: "todo", category: "reservation" },
  { item: "確認杭州宮宴 6/7 10:00 治裝與午宴場次", status: "todo", category: "reservation" },
  { item: "確認杭州 Pagoda君亭設計飯店 6/6-6/8 訂房細節", status: "todo", category: "hotel" },
  { item: "確認烏鎮民宿 6/8-6/10 是否含西柵門票與接駁", status: "todo", category: "hotel" },
  { item: "烏鎮入住時向老闆預約早茶客", status: "todo", category: "hotel" },
  { item: "確認上海中心J飯店 6/10-6/11 訂房細節", status: "todo", category: "hotel" },
  { item: "查詢上海虹橋到杭州高鐵", status: "todo", category: "transport" },
  { item: "安排杭州到烏鎮交通", status: "todo", category: "transport" },
  { item: "安排烏鎮到上海中心J飯店交通", status: "todo", category: "transport" },
];
